### ISSUE TITLE
Simultaneous connections supported

### ISSUE THREAD

**Issue by SorteHarshada** [redsolution/xabber-websocket#10]
Hello,
How many simlutaneous connections are supported by xabber websocket?. Is there any configuration which can be changed for connections? If yes, please tell me where.

**Comment by oxoWrk** [comment]
Maximum number of connections is limited by OS and Erlang.
Look at this [this]( http://erlang.org/documentation/doc-9.2/doc/efficiency_guide/advanced.html#ports)
