### ISSUE TITLE
Websocket Server Crashes

### ISSUE THREAD

**Issue by NeemitShastri** [redsolution/xabber-websocket#3]
Hi,

I have setup xabber-websocket with nginx as proxypass, 
at start the ram usage is low but after few days ram usage gets high and it crashes the server.

the number of jabber users are constant.

System Config (AWS ec2 Instance):
Core: 2
RAM: 4 GB
OS:- Ubuntu 16.04 64 BIT

Thanks.

**Comment by oxoWrk** [comment]
how many online users?
xabber-ws version ?

**Comment by NeemitShastri** [comment]
around 80 to 90 users

**Comment by oxoWrk** [comment]
xabber-ws version ?

**Comment by NeemitShastri** [comment]
xabber-websocket 0.1

**Comment by oxoWrk** [comment]
very strange. I have low memory usage (~50MB) with more than 100 connections
Do you have any  memory usage data by xabber-ws

**Comment by NeemitShastri** [comment]
the ram usage is low at start of websocket server around 400mb, but after few days the ram usage increases and server crashes

**Comment by oxoWrk** [comment]
try to use [observer](http://erlang.org/doc/apps/observer/observer_ug.html) to understand what is using the memory

**Comment by NeemitShastri** [comment]
Thanks have started monitoring the memory using observer :)
