### ISSUE TITLE
Change the log level

### ISSUE THREAD

**Issue by SorteHarshada** [redsolution/xabber-websocket#9]
I want to change the log level in xabber websocket. Where to find the log level configuration?.
My connection via xabber websocket is failing while connecting from jmeter but working fine with my application. So i want to see the logs why it is failing , which is not generated in current scenario.

**Comment by oxoWrk** [comment]
../xabber_ws/config/xabber_ws.config

`  {lager, [
    {handlers, [
      {lager_console_backend, [{level, info}]}
    ]}
  ]}
`
